# Quick Start (at fist stop ROS Master if working on host)
# $ docker compose -f compose.rosbot.simulation.yaml -f compose.rosbot.mapping.yaml up

services:

  bridge:
    image: husarion/ros:galactic-ros1-bridge
    restart: on-failure
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
      - RMW_IMPLEMENTATION
    command: ros2 run ros1_bridge dynamic_bridge

  ros-master:
    image: ros:noetic-ros-core
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
    command: stdbuf -o L roscore

  rosbot_simulation:
    image: husarion/rosbot:melodic-simulation
    restart: on-failure
    runtime: nvidia
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
      - ROS_MASTER_URI=http://ros-master:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      roslaunch --wait rosbot_bringup rosbot.launch 
        world:=/ros_ws/src/rosbot_gazebo/worlds/maze.world
