services:

  flash-fw:
    build:
      context: ./../
      dockerfile: ./Dockerfile
    privileged: true
    environment:
      - SERIAL_PORT
    devices:
      - ${SERIAL_PORT}
    command: >
      python3 ./../flash-firmware.py /root/firmware_diff.bin 
