name: Build/Publish Docker Image 

on: push
  # push:
  #   branches:
  #     - 'main'
  
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
    
    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: print docker version
      run: docker --version

    - name: print docker buildx version
      run: docker buildx version   

    - name: build docker image
      run: >
        docker buildx build
        --platform linux/amd64
        -t rosbot-docker-test
        .

    # - name: Build and push
    #   uses: docker/build-push-action@v2
    #   with:
    #     platforms: linux/amd64
    #     push: true
    #     no-cache: true
    #     tags: husarion/rosbot:latest
        
        # cache-from: type=registry,ref=husarion/rosbot
        # cache-to: type=inline